# Generated by Django 2.2.3 on 2019-11-29 12:27

import apps.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Pending for Approval'), (3, 'Rejected'), (4, 'Approved')], default=1, verbose_name='Status')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Pending for Approval'), (3, 'Rejected'), (4, 'Approved')], default=1, verbose_name='Status')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('lease_name', models.CharField(max_length=120, verbose_name='Lease name')),
                ('comp_model', models.CharField(max_length=50, verbose_name='Comp Model')),
                ('comp_serial_number', models.CharField(max_length=70, verbose_name='Comp Serial Number')),
                ('engine_model', models.CharField(max_length=50, verbose_name='Engine Model')),
                ('engine_serial_number', models.CharField(max_length=50, verbose_name='Engine Serial Number')),
                ('additional_notes', models.CharField(blank=True, max_length=255, verbose_name='Additional Notes')),
                ('customer_signature', models.ImageField(upload_to=apps.api.models.get_customer_signature_img_path, verbose_name='Customer Signature')),
                ('customer_printed_name', models.CharField(max_length=120, verbose_name='Customer Printed Name')),
                ('future_work_needed', models.CharField(max_length=255, verbose_name='Future Work Needed')),
                ('what_was_found', models.CharField(max_length=255, verbose_name='What Was Found')),
                ('what_was_performed', models.CharField(max_length=255, verbose_name='What Was Performed')),
                ('what_was_the_call', models.CharField(max_length=255, verbose_name='What Was the Call')),
                ('connected_job', models.ForeignKey(help_text='This is connected job', on_delete=django.db.models.deletion.PROTECT, to='api.Job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Service Ticket',
                'verbose_name_plural': 'Service Tickets',
            },
        ),
    ]
