# Generated by Django 2.2.3 on 2019-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191127_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='locations',
            field=models.ManyToManyField(to='api.Location', verbose_name='Locations'),
        ),
    ]
