# Generated by Django 2.2.3 on 2019-11-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191129_1227'),
        ('api', '0003_auto_20191128_1541'),
    ]

    operations = [
    ]
