# Generated by Django 2.2.3 on 2019-11-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20191129_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='customer',
        ),
    ]
