# Generated by Django 2.2.3 on 2019-12-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191203_1541'),
    ]

    operations = [
    ]
