# Generated by Django 2.2.3 on 2019-12-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191204_1524'),
        ('api', '0008_merge_20191205_1140'),
    ]

    operations = [
    ]
