# Generated by Django 2.2.3 on 2019-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20191205_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers', to='authentication.Manager', verbose_name='Managers'),
        ),
        migrations.AddField(
            model_name='job',
            name='mechanics',
            field=models.ManyToManyField(blank=True, related_name='mechanics', to='authentication.Mechanic', verbose_name='Mechanics'),
        ),
    ]
