# Generated by Django 2.2.3 on 2019-12-11 15:51

import apps.api.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191209_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Pending for Approval'), (3, 'Rejected'), (4, 'Approved')], default=1, validators=[apps.api.model_validators.validate_request_job_perm], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
