# Generated by Django 2.2.3 on 2019-12-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191209_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_set_pending_for_approval', 'Can set status Pending for Approval')]},
        ),
    ]
