# Generated by Django 2.2.3 on 2019-12-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191211_1427'),
        ('api', '0012_auto_20191211_1247'),
    ]

    operations = [
    ]
