# Generated by Django 2.2.3 on 2019-12-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191211_1551'),
        ('api', '0013_merge_20191212_0941'),
    ]

    operations = [
    ]
