# Generated by Django 2.2.3 on 2019-12-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20191212_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_set_pending_for_approval_job', 'Can set Job status Pending for Approval')]},
        ),
        migrations.AlterModelOptions(
            name='serviceticket',
            options={'permissions': [('can_set_pending_for_approval_service_ticket', 'Can set Service Ticket status Pending for Approval'), ('add_mechanic_to_service_ticket', 'Add mechanic to the Service Ticket'), ('can_approve_service_ticket', 'Can approve Service Ticket'), ('can_reject_service_ticket', 'Can reject Service Ticket')], 'verbose_name': 'Service Ticket', 'verbose_name_plural': 'Service Tickets'},
        ),
    ]
