# Generated by Django 2.2.3 on 2019-12-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191212_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number_starting_point', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Job number starting point')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
