# Generated by Django 2.2.3 on 2019-12-20 14:19

import apps.api.models
import apps.utils.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_create_settings_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='comp_serial_number',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='engine_serial_number',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='aux_temp',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Aux Temp'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='comp_serial',
            field=models.CharField(blank=True, max_length=120, verbose_name='Comp Serial #'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='compressor_oil_pressure',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Compressor Oil Pressure / Kill'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='compressor_oil_temp',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Compressor Oil Temp'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='county',
            field=models.CharField(blank=True, max_length=120, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='customer_po_wo',
            field=models.CharField(blank=True, max_length=120, verbose_name='Customer PO/WO'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='cylinder_temperature_hi1',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='cylinder_temperature_hi2',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='cylinder_temperature_hi3',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='cylinder_temperature_hi4',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='discharge1',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Discharge'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='discharge2',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Discharge'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='discharge3',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Discharge'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='engine_oil_pressure',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Enfine Oil Pressure / Kill'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='engine_oil_temp',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Engine Oil Temp'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='engine_serial',
            field=models.CharField(blank=True, max_length=120, verbose_name='Engine Serial #'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='exhaust_temperature_hi',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='exhaust_temperature_l',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='exhaust_temperature_r',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='hour_meter_reading',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Hour Meter Reading'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='jacket_water_pressure',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Jacket Water Pressure'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='kandr_wo',
            field=models.CharField(blank=True, max_length=120, verbose_name='K&R WO#'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='lo_hi',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='LO/HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='manifold_pressure_hi1',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='manifold_pressure_hi2',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='manifold_pressure_l',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='manifold_pressure_r',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='manifold_temperature_hi',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='manifold_temperature_l',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='manifold_temperature_r',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='mmcfd',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='MMCFD'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='rpm',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='RPM'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_hi1',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_hi2',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_hi3',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_hi4',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_hi5',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='HI'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_lo1',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='LO'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_lo2',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='LO'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_lo3',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='LO'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_lo4',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='LO'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='safety_setting_lo5',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='LO'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'AL'), (2, 'AK'), (3, 'AZ'), (4, 'AR'), (5, 'CA'), (6, 'CO'), (7, 'CT'), (8, 'DC'), (9, 'DE'), (10, 'FL'), (11, 'GA'), (12, 'HI'), (13, 'ID'), (14, 'IL'), (15, 'IN'), (16, 'IA'), (17, 'KS'), (18, 'KY'), (19, 'LA'), (20, 'ME'), (21, 'MD'), (22, 'MA'), (23, 'MI'), (24, 'MN'), (25, 'MS'), (26, 'MO'), (27, 'MT'), (28, 'NE'), (29, 'NV'), (30, 'NH'), (31, 'NJ'), (32, 'NM'), (33, 'NY'), (34, 'NC'), (35, 'ND'), (36, 'OH'), (37, 'OK'), (38, 'OR'), (39, 'PA'), (40, 'RI'), (41, 'SC'), (42, 'SD'), (43, 'TN'), (44, 'TX'), (45, 'UT'), (46, 'VT'), (47, 'VA'), (48, 'WA'), (49, 'WV'), (50, 'WI'), (51, 'WY')], null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='suction',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Suction'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='td1',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TD1'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='td2',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TD2'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='td3',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TD3'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='td4',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TS4'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ts1',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TS1'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ts2',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TS2'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ts3',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TS3'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ts4',
            field=apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='TS4'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='unit_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unit Hours'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='comp_model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Comp Model'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_service_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='customer_printed_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Customer Printed Name'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='customer_signature',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.models.get_customer_signature_img_path, verbose_name='Customer Signature'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='engine_model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Engine Model'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='future_work_needed',
            field=models.CharField(blank=True, max_length=255, verbose_name='Future Work Needed'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='lease_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lease Name'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='what_was_found',
            field=models.CharField(blank=True, max_length=255, verbose_name='What Was Found'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='what_was_performed',
            field=models.CharField(blank=True, max_length=255, verbose_name='What Was Performed'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='what_was_the_call',
            field=models.CharField(blank=True, max_length=255, verbose_name='What Was the Call'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='who_called',
            field=models.CharField(blank=True, max_length=120, verbose_name='Who Called?'),
        ),
        migrations.CreateModel(
            name='EmployeeWorkBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('mileage', apps.utils.fields.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Mileage')),
                ('hotel', models.BooleanField(blank=True, null=True, verbose_name='Hotel')),
                ('per_diem', models.BooleanField(blank=True, null=True, verbose_name='Per Diem')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.Mechanic', verbose_name='Employee')),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_works', to='api.ServiceTicket')),
            ],
        ),
    ]
