# Generated by Django 2.2.3 on 2019-12-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191220_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=2400, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='future_work_needed',
            field=models.CharField(blank=True, max_length=500, verbose_name='Future Work Needed'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='what_was_found',
            field=models.CharField(blank=True, max_length=1000, verbose_name='What Was Found'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='what_was_performed',
            field=models.CharField(blank=True, max_length=1000, verbose_name='What Was Performed'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='what_was_the_call',
            field=models.CharField(blank=True, max_length=290, verbose_name='What Was the Call'),
        ),
    ]
