# Generated by Django 2.2.3 on 2020-01-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_attachment'),
        ('api', '0020_auto_20200109_1310'),
    ]

    operations = [
    ]
