# Generated by Django 2.2.3 on 2020-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20200110_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='reject_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Reject description'),
        ),
    ]
