# Generated by Django 2.2.3 on 2020-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_serviceticket_reject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'AK'), (2, 'AL'), (3, 'AR'), (4, 'AZ'), (5, 'CA'), (6, 'CO'), (7, 'CT'), (8, 'DC'), (9, 'DE'), (10, 'FL'), (11, 'GA'), (12, 'HI'), (13, 'IA'), (14, 'ID'), (15, 'IL'), (16, 'IN'), (17, 'KS'), (18, 'KY'), (19, 'LA'), (20, 'MA'), (21, 'MD'), (22, 'ME'), (23, 'MI'), (24, 'MN'), (25, 'MO'), (26, 'MS'), (27, 'MT'), (28, 'NC '), (29, 'ND'), (30, 'NE '), (31, 'NH '), (32, 'NJ '), (33, 'NM '), (34, 'NV'), (35, 'NY'), (36, 'OH'), (37, 'OK'), (38, 'OR'), (39, 'PA'), (40, 'RI'), (41, 'SC'), (42, 'SD'), (43, 'TN'), (44, 'TX'), (45, 'UT'), (46, 'VA'), (47, 'VT'), (48, 'WA'), (49, 'WI'), (50, 'WV'), (51, 'WY')], null=True, verbose_name='State'),
        ),
    ]
