# Generated by Django 2.2.3 on 2020-01-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200122_1401'),
        ('api', '0023_auto_20200123_1247'),
    ]

    operations = [
    ]
