# Generated by Django 2.2.3 on 2020-01-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200122_1401'),
        ('api', '0023_auto_20200116_1511'),
    ]

    operations = [
    ]
