# Generated by Django 2.2.3 on 2020-01-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20200124_1404'),
        ('api', '0024_merge_20200124_1327'),
    ]

    operations = [
    ]
