# Generated by Django 2.2.3 on 2020-01-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20200124_1429'),
        ('api', '0022_auto_20200115_1356'),
    ]

    operations = [
    ]
