# Generated by Django 2.2.3 on 2020-01-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20200124_1429'),
        ('api', '0024_merge_20200124_1259'),
    ]

    operations = [
    ]
