# Generated by Django 2.2.3 on 2020-01-30 16:38

import apps.api.model_validators
import apps.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20200129_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.api.utils.get_file_attachment_path, validators=[apps.api.model_validators.validate_attachment_file_type], verbose_name='File'),
        ),
    ]
