# Generated by Django 2.2.3 on 2020-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20200124_1552'),
        ('api', '0026_merge_20200129_1617'),
    ]

    operations = [
    ]
