# Generated by Django 2.2.3 on 2020-01-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20200131_1424'),
        ('api', '0027_auto_20200130_1638'),
    ]

    operations = [
    ]
