# Generated by Django 2.2.3 on 2020-02-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20200131_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_set_pending_for_approval_job', 'Can set Job status Pending for Approval'), ('can_archive_jobs', 'Can set Archive Jobs'), ('can_restore_jobs', 'Can set Restore Jobs')]},
        ),
    ]
