# Generated by Django 2.2.3 on 2020-02-13 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_auto_20200204_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_relate_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serviceticket_relate_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_relate_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serviceticket_relate_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
