# Generated by Django 2.2.3 on 2020-03-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200213_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='kandr_wo',
        ),
    ]
