# Generated by Django 2.2.3 on 2020-03-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_ST_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkblock',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Mechanic', verbose_name='Employee'),
        ),
    ]
