# Generated by Django 2.2.3 on 2020-03-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_serviceticket_kandr_wo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='approved_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ST was approved'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='submitted_for_approval_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ST was submitted for approval'),
        ),
    ]
