# Generated by Django 2.2.3 on 2020-04-01 16:44

import apps.api.model_validators
import apps.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200213_13270'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=apps.api.utils.get_file_attachment_path, validators=[apps.api.model_validators.validate_attachment_file_type], verbose_name='File'),
        ),
    ]
