# Generated by Django 2.2.3 on 2020-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200324_1154'),
        ('api', '0034_auto_20200401_1644'),
    ]

    operations = [
    ]
