# Generated by Django 2.2.3 on 2021-12-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_employee_work_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBLockDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_date', models.DateField(blank=True, null=True, verbose_name='DB Lock Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
