# Generated by Django 2.2.3 on 2023-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_dblockdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Request date'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='future_work_needed',
            field=models.CharField(blank=True, max_length=500, verbose_name='Parts Used'),
        ),
    ]
