# Generated by Django 2.2.3 on 2019-11-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirectHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('date', models.DateField(verbose_name='Date')),
                ('hours', models.PositiveIntegerField(verbose_name='Spent Hours')),
                ('time_code', models.CharField(max_length=20, verbose_name='Time Code')),
                ('notes', models.CharField(max_length=255, verbose_name='Notes')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Mechanic')),
            ],
            options={
                'verbose_name': 'Indirect Hours',
                'verbose_name_plural': 'Indirect Hours',
            },
        ),
    ]
