# Generated by Django 2.2.3 on 2020-01-06 13:11

from django.db import migrations

from apps.authentication.group_permissions import update_group_permissions


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_auto_20200106_1242'),
    ]

    operations = [
        migrations.RunPython(update_group_permissions),
    ]
