# Generated by Django 2.2.3 on 2020-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0006_auto_20200115_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirecthours',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Is archive'),
        ),
    ]
