# Generated by Django 2.2.3 on 2020-02-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0007_indirecthours_is_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indirecthours',
            options={'permissions': [('can_approve_indirect_hours', 'Can approve Indirect Hours'), ('can_reject_indirect_hours', 'Can reject Indirect Hours'), ('can_archive_indirect_hours', 'Can set Archive IndirectHours'), ('can_restore_indirect_hours', 'Can set Archive IndirectHours')], 'verbose_name': 'Indirect Hours', 'verbose_name_plural': 'Indirect Hours'},
        ),
    ]
