# Generated by Django 2.2.3 on 2020-02-06 09:23

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from apps.authentication.models import User, Admin
from apps.api.models import Job, Attachment
from apps.notifications.models import Action
from apps.time_tracker.models import IndirectHours


ADMIN_PERMISSIONS = [
    (Admin, ('can_archive_users')),
    (Admin, ('can_restore_users')),
    (Admin, ('can_get_reports')),
    (Action, ('add_action')),
    (Action, ('view_action')),
    (Action, ('change_action')),
    (Action, ('delete_action')),
    (IndirectHours, ('can_archive_indirect_hours')),
    (IndirectHours, ('can_restore_indirect_hours')),
    (Attachment, ('add_attachment')),
    (Attachment, ('view_attachment')),
    (Attachment, ('change_attachment')),
    (Attachment, ('delete_attachment')),
    (Job, ('can_set_pending_for_approval_job')),
    (Job, ('can_archive_jobs')),
    (Job, ('can_restore_jobs')),
]

def update_admin_group_perms(apps, _):
    # add a custom permission to Admin's group
    admin_group = Group.objects.get(name='Admin')
    for codename in ADMIN_PERMISSIONS:
        content_type = ContentType.objects.get_for_model(codename[0])
        custom_perm, created = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename[1]
        )
        admin_group.permissions.add(custom_perm)

class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0008_auto_20200204_1036'),
    ]

    operations = [
        migrations.RunPython(update_admin_group_perms)
    ]
