# Generated by Django 2.2.3 on 2020-02-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0010_auto_20200206_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirecthours',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Spent Hours'),
        ),
    ]
