# Generated by Django 2.2.3 on 2020-03-18 15:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0011_auto_20200226_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirecthours',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Spent Hours'),
        ),
    ]
