# Generated by Django 2.2.3 on 2020-03-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0012_auto_20200313_1531'),
        ('time_tracker', '0012_auto_20200319_1252'),
    ]

    operations = [
    ]
