# Generated by Django 2.2.3 on 2020-03-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0013_merge_20200319_1417'),
        ('time_tracker', '0012_auto_20200318_1525'),
    ]

    operations = [
    ]
