# Generated by Django 2.2.3 on 2020-04-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0014_merge_20200324_1426'),
        ('time_tracker', '0014_merge_20200324_1318'),
    ]

    operations = [
    ]
