# Generated by Django 2.2.3 on 2020-05-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0015_merge_20200401_1051'),
        ('time_tracker', '0013_auto_20200521_2108'),
    ]

    operations = [
    ]
