# Generated by Django 3.2.23 on 2024-02-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0017_auto_20240207_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indirecthours',
            old_name='mechanic',
            new_name='mechanic_old',
        ),
    ]
