# Generated by Django 2.2.3 on 2019-11-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_update_group_permissions0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biller',
            options={'verbose_name': 'Biller', 'verbose_name_plural': 'Billers'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterModelOptions(
            name='mechanic',
            options={'verbose_name': 'Mechanic', 'verbose_name_plural': 'Mechanics'},
        ),
    ]
