# Generated by Django 2.2.3 on 2019-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20191129_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_confirmed_email',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
    ]
