# Generated by Django 2.2.3 on 2019-12-02 16:47

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def update_biller_and_manager_group_perms(apps, _):
    # add a custom permission to Biller's group
    biller_group = Group.objects.get(name='Biller')
    Biller = apps.get_model('authentication', 'Biller')
    custom_perm, created = Permission.objects.get_or_create(
        codename='can_set_pending_for_approval',
        content_type=ContentType.objects.get_for_model(Biller, for_concrete_model=False)
    )
    biller_group.permissions.add(custom_perm)

    # add a custom permission to Manager's group
    manager_group = Group.objects.get(name='Manager')
    Manager = apps.get_model('authentication', 'Manager')
    custom_perm, created = Permission.objects.get_or_create(
        codename='can_set_pending_for_approval',
        content_type=ContentType.objects.get_for_model(Manager, for_concrete_model=False)
    )
    manager_group.permissions.add(custom_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20191202_1407'),
    ]

    operations = [
        migrations.RunPython(update_biller_and_manager_group_perms)
    ]
