# Generated by Django 2.2.3 on 2019-12-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_custom_permissions_to_biller_and_manager_models'),
        ('authentication', '0009_add_first_user_to_admin_group'),
    ]

    operations = [
    ]
