# Generated by Django 2.2.3 on 2019-12-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_merge_20191205_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biller',
            options={'verbose_name': 'Biller', 'verbose_name_plural': 'Billers'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
