# Generated by Django 2.2.3 on 2019-12-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20191211_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superuser',
            fields=[
            ],
            options={
                'verbose_name': 'Superuser',
                'verbose_name_plural': 'Superusers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
    ]
