# Generated by Django 2.2.3 on 2020-01-03 16:40

from django.db import migrations


def change_user_roles_order_in_db(apps, _):
    """
    This migration make user roles order in db depend on our code implementation.
    USER_ROLES = (
        (1, 'Admin',),
        (2, 'Biller',),
        (3, 'Manager',),
        (4, 'Mechanic',),
        (5, 'Superuser',),
    )
    """
    Group = apps.get_model('auth', 'Group')
    first_group = Group.objects.get(id=1)
    first_group.name = 'Admin'
    first_group.save()
    second_group = Group.objects.get(id=2)
    second_group.name = 'Biller'
    second_group.save()
    third_group = Group.objects.get(id=3)
    third_group.name = 'Manager'
    third_group.save()
    fourth_group = Group.objects.get(id=4)
    fourth_group.name = 'Mechanic'
    fourth_group.save()
    fifth_group = Group.objects.get(id=5)
    fifth_group.name = 'Superuser'
    fifth_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_status'),
    ]

    operations = [
        migrations.RunPython(change_user_roles_order_in_db),
    ]
