# Generated by Django 2.2.3 on 2020-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20200115_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_email_notifications',
            field=models.BooleanField(default=True, verbose_name='Sent Email Notifications'),
        ),
    ]
