# Generated by Django 2.2.3 on 2020-02-11 14:49

from django.db import migrations

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from apps.api.models import Job


ADMIN_PERMISSIONS = [
    (Job, ('can_set_pending_for_approval_job'))
]

def update_admin_group_perms(apps, _):
    # add a custom permission to Admin's group
    admin_group = Group.objects.get(name='Admin')
    for codename in ADMIN_PERMISSIONS:
        content_type = ContentType.objects.get_for_model(codename[0])
        custom_perm, created = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename[1]
        )
        admin_group.permissions.add(custom_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20200204_1036'),
    ]

    operations = [
        migrations.RunPython(update_admin_group_perms)
    ]
