# Generated by Django 2.2.3 on 2020-04-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20200211_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_push_notifications',
            field=models.BooleanField(default=True, verbose_name='Sent Push Notifications'),
        ),
    ]
