# Generated by Django 2.2.3 on 2020-03-20 16:41
from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from apps.authentication.models import Biller, Manager


BILLER_PERMISSIONS = [
    (Biller, ('can_get_reports'))
]

MANAGER_PERMISSIONS = [
    (Manager, ('can_get_reports'))
]


def update_biller_group_perms(apps, _):
    # add a custom permission to Biller's group
    biller_group = Group.objects.get(name='Biller')
    for codename in BILLER_PERMISSIONS:
        content_type = ContentType.objects.get_for_model(codename[0])
        custom_perm, created = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename[1]
        )
        biller_group.permissions.add(custom_perm)


def update_manager_group_perms(apps, _):
    # add a custom permission to Manager's group
    manager_group = Group.objects.get(name='Manager')
    for codename in MANAGER_PERMISSIONS:
        content_type = ContentType.objects.get_for_model(codename[0])
        custom_perm, created = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename[1]
        )
        manager_group.permissions.add(custom_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20200211_1449'),
    ]

    operations = [
        migrations.RunPython(update_biller_group_perms),
        migrations.RunPython(update_manager_group_perms)
    ]
