# Generated by Django 2.2.3 on 2020-03-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20200319_1252'),
        ('authentication', '0021_auto_20200320_1641'),
    ]

    operations = [
    ]
