# Generated by Django 2.2.3 on 2020-04-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_merge_20200324_1318'),
        ('authentication', '0022_merge_20200324_1426'),
    ]

    operations = [
    ]
