# Generated by Django 2.2.3 on 2020-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_user_sent_push_notifications'),
        ('authentication', '0023_merge_20200401_1051'),
    ]

    operations = [
    ]
