# Generated by Django 2.2.3 on 2020-04-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_merge_20200407_1442'),
        ('authentication', '0024_merge_20200407_1437'),
    ]

    operations = [
    ]
