# Generated by Django 3.2.23 on 2024-02-02 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_add_permission_can_get_time_report_for_mech'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
