# Generated by Django 2.2.3 on 2020-01-17 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('object_type', models.PositiveSmallIntegerField(choices=[(0, 'Account'), (1, 'Job'), (2, 'Service Ticket'), (3, 'Indirect Hour')], default=2, verbose_name='Object type')),
                ('connected_object_id', models.PositiveIntegerField(verbose_name='Connected object id')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('connected_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Connected Users')),
            ],
        ),
    ]
