# Generated by Django 2.2.3 on 2020-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Is viewed'),
        ),
    ]
