# Generated by Django 2.2.3 on 2020-01-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_action_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='object_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Job'), (1, 'Service Ticket'), (2, 'Indirect Hour')], verbose_name='Object type'),
        ),
    ]
